### ISSUE TITLE
O_NONBLOCK + active waiting = broken

### ISSUE THREAD

**Issue by michael-dev** [ClusterLabs/libqb#139] opened 2015-02-22 12:11 UTC
Summary: libqb 0.17.1 sets O_NONBLOCK on unix sockets accepted by qb_ipcs_us_connection_acceptor using qb_sys_fd_nonblock_cloexec_set but then does active waiting with recvmsg in qb_ipcs_us_connection_acceptor -> qb_ipcs_uc_recv_and_auth -> qb_ipc_us_recv_msghdr (and possibly others) to block until a message is received. This leads to high cpu load and bad performance when used with a realtime (corosync) process, as the non-realtime client (pacemaker) will not be able to actually submit the message due to load.

Details:
With commit 177ef0e5240b4060ff5b14eab6f2eefee3aa777d , corosync makes realtime priority a default. This breaks corosync for running on single-core machines for me, as corosync will eat 100% of the cpu and pacemaker will almost not advance.

Using callgrind, I compared a few seconds after startup of corosync with and without realtime priority (using the -p switch). Corosync was run with -f for debugging.
The main difference I found is in qb_ipcs_us_connection_acceptor, where 155 calls of qb_ipcs_us_connection_acceptor have an extra of 10 000 000 calls to recvmsg when run with realtime priority.

The way to call recvmsg in qb_ipcs_us_connection_acceptor is by inlining qb_ipcs_us_connection_acceptor -> qb_ipcs_uc_recv_and_auth -> qb_ipc_us_recv_msghdr .
The recvmsg in qb_ipc_us_recv_msghdr has MSG_WAITALL and MSG_NOSIGNAL set and is looped until enough data is returned, so it should not be returning before the message is completed.

Looking at the AF_UNIX implementatation in the linux kernel (I'm running 3.2.0 from debian stable) [1], it looks like without a non-zero timeout set, recvmsg will not wait for data. But according to [2], a zero timeout value is default. I've found no setsockopt for SO_RCVTIMEO call in libqb 0.17.1, so the timeout should be zero.
To test this, I added a call to setsockopt setting SO_RCVTIMEO in qb_ipcs_us_connection_acceptor just before qb_ipcs_uc_recv_and_auth, setting the timeout to 30s. But this apparently did not help.

But adding a usleep(100) in qb_ipc_us_recv_msghdr before each "goto retry_recv;" line did help and makes corosync run smoothly again. Though this does not look like a viable solution.

Looking at qb_ipcc_us_setup_connect, I would not expect recvmsg to return partial data, so waitall should have no effect at all, as target in [1] will be >= 1 anyway (maybe this depends on the af_unix implementation).

But maybe qb_sys_fd_nonblock_cloexec_set setting NONBLOCK on new_fd breaks this. So I tested by removing O_NONBLOCK in the beginning of qb_ipc_us_recv_msghdr before recvmsg and readding O_NONBLOCK before returning from qb_ipc_us_recv_msghdr. This worked fine whether or not a receive timeout was set on the socket.

[1] http://lxr.free-electrons.com/source/net/unix/af_unix.c#L1985
[2] http://linux.die.net/man/3/setsockopt

**Comment by davidvossel** [comment] 2015-02-23 15:56
From what I'm gathering, this is a kernel scheduling issue not a libqb issue.  I don't entirely understand why switching from NONBLOCKING to BLOCKING mode during the socket read appears to fix the issue, but this is not an option for us.  If corosync is not yielding CPU cycles, then the priority needs to be adjusted. Also, corosync isn't the only consumer of libqb IPC.  The internal pacemaker components are ipc servers and clients to each other. Those components as well as others require this NONBLOCKING functionality. When processes are scheduled properly, NONBLOCKING actually increases performance quite a bit for us under load.

**Comment by sdake** [comment] 2015-02-23 18:20
My guess is switching from NONBLOCKING to BLOCKING reduces spinning in corosync or libqb, resulting in a much-less likely occurence of the problem.  I find it highly suspect changing that flag would actually resolve the issue.  If you change the flag to blocking perhaps something higher up the stack is calling that operation too excessively not allowing other things to schedule (other things being ipc  clients).

How about getting to the root cause?  I assume libqb has no threading model, atleast that is how it was supposed to be early on.  I have seen these lockups before and running without SCHED_RR fixes the problem.

This means there is a priority inversion somewhere in the execution of the code base.  My guess is somehow Corosync and Pacemaker are becoming inverted wrt libqb, but I'm not sure how to prove it.

I suggest investigating replacing spinlocks in hdb with mutexes.  The performance will suffer significantly, but it may fix the problem.  Again might just fix the symptom, - I'd track down why the blocking is spinning so much.

**Comment by sdake** [comment] 2015-02-23 18:22
The main difference I found is in qb_ipcs_us_connection_acceptor, where 155 calls of qb_ipcs_us_connection_acceptor have an extra of 10 000 000 calls to recvmsg when run with realtime priority.

Just throttle these recvmsg calls imo :)

**Comment by davidvossel** [comment] 2015-02-23 20:03
@sdake whoa... okay that sounds like the place. Can someone who's reproducing this easily give this patch a shot?

https://github.com/ClusterLabs/libqb/pull/141

**Comment by sdake** [comment] 2015-02-23 21:19
@dvossel,

Patch looks nice!  I'm not sure if it would work or not, but looks like it should and allow the services to busy-spin into their performance oriented goals ;) (libqb was made to be fast not effecient :)

**Comment by michael-dev** [comment] 2015-02-24 12:56
> How about getting to the root cause?

Look at the current code of qb_ipc_us_recv_msghdr: As long as there is no message in the socket, recvfrom will return -1 and errno=EAGAIN (according to man recvmsg). Thus a goto "retry_recv" is executed, and so this repeats just until recvmsg returns a message.

This is just busy waiting for a message and therefore blocks the application using libqb until a message is received.

By making the socket being blocking again, the application using libqb is no more blocked than it is right now. But instead of doing busy waiting in a realtime process, the application gets suspended until data actually received.

Look at the client implementation of libqb to verify this, I assume a realtime server and a non-realtime client.
The kernel will schedule:
1. The client opens the socket
2. The server accepts the connection (qb_ipcs_us_connection_acceptor)
3. The server is doing busy waiting to read the first message (qb_ipc_us_recv_msghdr)
4. Eventually, the client will be able to transmit the mesage. This will take a long time, due to the servers realtime priority blocking the client.
5. Now the server stops doing busy waiting.

While sched_yield will likely help mitigate the issue as it increases the probability of the client to be able to transmit the initial message, it does not address to root cause: libqb is still doing busy waiting. I do not see any benefit in doing busy waiting in qb_ipc_us_recv_msghdr over doing blocking.

Maybe an even better solution would be to defer qb_ipcs_uc_recv_and_auth in qb_ipcs_us_connection_acceptor until data is actually available on the socket.

**Comment by chrissie-c** [comment] 2016-01-08 13:22
Cosing as this was committed as merge request 141

**Closed by chrissie-c** 2016-01-08 13:22 UTC
